### ISSUE TITLE
Review

### ISSUE THREAD

**Issue by weijia-cheng** [chapkachapka/dorothy-m-richardson_backwater#1]
# Semantics

- [x] `chapter-2`: Bonsoir doesn’t need italics because it is in Merriam-Webster. 
- [x] `chapter-10`: Same thing with “au revoir.”
- [x] `chapter-3`: You marked `s` as a `z3998:phoneme` but it is actually a `z3998:grapheme`. Phoneme is for spoken units whereas grapheme is for written units.
- [x] `chapter-3`: Should `Standard I` not be italicized as a book? Also, I assume the `I` is a Roman numeral and should receive the appropriate semantics.
- [x] `chapter-2`: The verse quotation needs to use [the standard verse formatting](https://standardebooks.org/manual/1.7.3/7-high-level-structural-patterns#7.5). Each of the lines needs to be in its own span (you put all the lines in one big span). Make sure to add all of the standard CSS too.
- [x] `chapter-10`: You have “sotto voce” in an `<em>` but I am pretty sure that it was originally italicized as non-English. It is in M-W now so we can deitalicize it.
- [x] `chapter-5`: Very trivial, but instead of `’<em>ear</em>` I think `<em>’ear</em>` makes more sense. The entire word (albeit with a elision) is emphasized.
- [x] `chapter-5`: `In manus` should be marked as italics and Latin, not emphasis.

# Images

- [x] `se build-images` updates `cover.source.tif` and we should accept the changes.

# Commit History

- [x] ad91238219f6a3afc2b5309b5d0761ad25719ea7 I see a couple of problems here:

* Removing the space in “mob cap” is an editorial change. So is changing the capitalization of “saal” and “bürgers.” Adding semantics is a non-editorial change, so this commit mixes together editorial and non-editorial changes and will need a rebase.
* I’m not convinced the capitalization change for “saal” and “bürgers” is really necessary. I get that all nouns are capitalized in German but this is an English book. There are already examples in our corpus where a single quoted German word was kept in lowercase ([e.g.](https://github.com/standardebooks/erskine-childers_the-riddle-of-the-sands/blob/2c4da41abcdcf550dfb5e46c155640aabb58b785/src/epub/text/chapter-26.xhtml#L14)). Let’s leave these as originally printed.

# Colophon

- [x] Your name in the colophon should either link to your personal web page if you have one, or it should be wrapped in a `<b epub:type="z3998:personal-name">`.

# Metadata

- [x] Omit the trailing `/` from the IA source link. The colophon and imprint also need this correction.
- [x] We should remove the Autobiography subject per [Alex’s judgment](https://groups.google.com/g/standardebooks/c/ZkClwQYoZwI/m/Yy3GTKshCgAJ).
- [x] *Backwater* doesn’t actually have a Wikipedia page, from what I can tell. The Wikipedia link you included just links to the disambiguation page. (There is a *Backwater* (novel) page, but it isn’t this one.)

**Comment by chapkachapka** [comment]
Thanks very much, I've corrected these with the following exceptions:

1. The "poetry" in chapter 3 is from a book called Bell's Standard Elocutionist, you can see the original [here](https://www.google.com.au/books/edition/Bell_s_Standard_Elocutionist/V80EAQAAIAAJ?hl=en&gbpv=1&dq=Sicily&pg=PA457&printsec=frontcover). The narrator is commenting on the strange way it's printed in the original, as she says, "not divided up into verses"--i.e., printed all on one line. It wouldn't make sense to break it into verses for the SE edition because it's a very intentional effect to print it without them.
2. The German capitals are changed as they are to match the first volume in the series, which takes place mostly in Germany and where the "Saal" is very important (the word is in the first book about 50 times, always capitalised). Given that I think we need to keep them. If you read the two books in order a lowercase "saal" would definitely jar.
3.  I haven't yet done the rebase because I have not yet figured out how to. I've looked at the documentation around rebasing generally and I don't quite see how it applies to this situation.

All the documentation I can find assumes you've got a branch off a master and you want to rebase all of it back to the master. Do I need to create a branch before the problem commit, then rebase the master onto that branch? Can you maybe give me a high level set of steps and I can try to figure it out from that?

**Comment by weijia-cheng** [comment]
- [ ] Sorry, I referred to the wrong chapter for the verse. I meant the instance in chapter 2:

```
			<blockquote epub:type="z3998:verse">
				<p>
					<span>“She was his life,<br/>
					The ocean to the river of his thoughts⁠—<br/>
					Which terminated all.”<br/></span>
				</p>
			</blockquote>
```

- [x] For the Roman numeral span you added to *Standard I*, you are missing a forward slash in the closing tag.

# Rebasing

What we want to do here is an [interactive rebase](https://hackernoon.com/beginners-guide-to-interactive-rebasing-346a3f9c3a6d). (I recommend reading through this guide, it is pretty comprehensive for a beginner.) Interactive rebasing allows us to retroactively rewrite the commit history (this is necessary in our case because for SE repositories we need a clear separation of editorial commits from non-editorial commits. In our case, to start an interactive rebase, we would begin with the command

```
git rebase -i ad91238~
```

which will allow us to start rebasing starting from the problematic commit I mentioned. When you run this command you will see a text buffer like

```
pick ad91238 Add language coding
pick 661b141 [Editorial] modernize spelling and hyphenation
pick 05802d3 [Editorial] Modernize spelling and hyphenation
pick 1cb0124 Add cover image and associated metadata
pick 59af193 Fill in additional metadata; add source image
pick 52a33bc Add semantics and standardise formatting
pick e9d0441 [Editorial] Modernise spacing, hyphenation and capitalisation
pick b803145 Adjust markup
pick a9fc4bc [Editorial] Corrected titles of "Cinq-Mars" and "A Psalm of Life"
pick 6b328a6 [Editorial] Correct titlecasing in work referenced in text
pick 04ed66f Create lint-ignore file for unnecessary warning
pick 18732ee [Editorial] Remove subchapter numbers
pick 8d9c497 Fix markup errors
pick a318a79 [Editorial] Modernise hyphenation
pick ecd6f9c Re-run Typogrify
pick 13249a2 Fix spacing issue in personal initials.
pick edf0324 Add transcriber's note.
pick fbd592b Remove subchapter markup
pick cdf920a Update cover.source.tif
pick 729d688 Modify metadata and colophon
pick 97adf31 Correct metadata and semantics per review
```

You will need to change the `pick` in the `pick ad91238 Add language coding` to `edit`, then save the file. (By default, git uses the `vi` text editor. If you aren't familiar with it, the guide explains how to use `vi` for this purpose.)

Once you save and exit the text buffer with `:wq`, you will begin the interactive rebase. During your interactive rebase, you need to remove all of the editorial changes I mentioned from the "Add language coding" commit. This means that you will *temporarily* undo the capitalization changes and the "mob cap" change. Once you've undone those changes, you will need to use `git add` and `git commit --amend` to modify the ad91238 commit. This will make it so that the final, amended commit will no longer have any editorial changes.

You then will run `git rebase --continue` and from there the rebase process will continue automatically. I believe you will have to work through a merge conflict once you get to the removing subchapters commit. The beginner's guide explains a bit of how to fix a merge commit, but basically what you are going to do is rewrite the removing subchapters commit so that it becomes consistent with the rewritten "Add language coding" commit.

Once you've resolved the merge conflict and completed the interactive rebase, your local commit history will be different from the remote commit history on GitHub. You will have to use `git push --force` to push your updated commit history to GitHub. Anyways once you've gotten to that point you can add back your editorial changes in a separate commit (properly annotated as Editorial this time around!)

If this sounds like an enormous hassle... I'm sorry to say that it really is one. That's why the step-by-step guide places such emphasis on keeping commits small and separating editorial and non-editorial commits. Interactive rebasing isn't too bad once you've become experienced with git (I use it professionally so I have lots of experience) but can be very difficult for a beginner, and I have seen some productions get derailed because of the need for a rebase. Let me know if you have any questions or need more detailed instructions at any point. In the worst case, if you can't figure it out, I have a copy of your repository on my computer and I can do the rebase on my end.

**Comment by chapkachapka** [comment]
Okay, an update--I think I was able to figure out the rebasing process, and I've done the rebase and then resubmitted those changes as two separate commits. I took a backup before I started and ran a diff, and it doesn't look like I've screwed anything else up in the process.

So I think I've addressed everything except points 1 and 2 above.

**Comment by weijia-cheng** [comment]
Ok, the rebase looks good! As for points 1 and 2:

1. I agree that the verse in chapter 3 has intentional styling and shouldn't be changed. That was a typo on my part, and I actually mean the verse in chapter 2, which does have breaks ("She was his life" etc.). That one does need to conform to the verse formatting in the manual.
2. That capitalization change makes sense if it is for consistency between volumes.

So the only outstanding issue is #1. Once you have fixed that, I will do a final check for anything else left over, otherwise I will forward to Alex.

**Comment by chapkachapka** [comment]
Fixed the verse formatting and CSS; also corrected the IA tag in a few additional places that popped up on Lint once I fixed it in content.opf.

**Comment by weijia-cheng** [comment]
Ok, I noticed one last issue. `typogrify` adds a word joiner before a hair space in chapter-1, and that change should be accepted. Once you have that fixed we are good to go.

**Comment by chapkachapka** [comment]
Okay, should be fixed.
